config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :sessions

  resources :questions do
    resources :answers
  end
  
  resources :tags

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :response, :presence => true
  after_create :send_notification_email

  def upvote
    self.votes += 1
  end

  def downvote
    self.votes -= 1
  end

  def send_notification_email

    UserMailer.notification_mailer(self.question.user, self.question).deliver_now
    question = self.question
    user = question.user
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_and_belongs_to_many :tags



  validates :title, :presence => true
  validates :body, :presence => true

  def upvote
    self.votes += 1
  end

  def downvote
    self.votes -= 1
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :questions

  validates :name, :presence => true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


  validates_uniqueness_of :email, :username

  after_create :send_confirmation_email

  def send_confirmation_email
    UserMailer.signup_confirmation(self).deliver_now
  end




end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize, only: [:edit, :new, :create, :destroy]
  before_action :set_default, only: [:edit, :update, :destroy]

  def new
  end


  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    if @answer.save
      flash[:success] = "Your answer has been added"
      redirect_to :back
    else
      flash[:danger] = "Oops, something went wrong, please try again."
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if params[:vote] == 'up'
      @answer.upvote
      @answer.save
      redirect_to question_path(@question)
    else params[:vote] == 'down'
      @answer.downvote
      @answer.save
      redirect_to question_path(@question)
    end

  end

  private

  def set_default
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:response)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    if current_user.nil?
      flash[:danger]="You must be logged in to do that"
      redirect_to new_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tags = Tag.all
    @questions = Question.all.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize, only: [:edit, :new, :create, :destroy]
  before_action :set_default, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def new
    @question = Question.new

  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:success] = "Your question was added"
      redirect_to root_path
    else
      flash[:danger] = "Oops, something went wrong and your question wasn't added."
      render :new
    end
  end

  def show
    @user = @question.user
    @answers = @question.answers
    @answer = Answer.new
  end

  def edit

  end

  def update
    if params[:vote] == 'up'
      @question.upvote
      @question.save
      redirect_to question_path(@question)
    elsif params[:vote] == 'down'
      @question.downvote
      @question.save
      redirect_to question_path(@question)
    elsif @question.update(question_params)
      flash[:success] = "Question change saved"
      redirect_to question_path(@question)
    else
      flash[:danger] = "Something went wrong and the changes were not saved."
      redirect_to :back
    end
  end

  def destroy
    if @question.answers.any?
      @question.answers.each do |answer|
        answer.destroy

      end
      @question.destroy
      flash[:success] = "Question deleted"
      redirect_to root_path
    elsif @question.destroy
      flash[:success] = "Question deleted"
      redirect_to root_path
    else
      flash[:danger] = "Something went wrong and the question was not deleted"
      redirect_to :back
    end
  end


  private

  def set_default
    @questions = Question.all
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :tag_ids =>[])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'You are now logged in'
      redirect_to "/"
    else
      flash[:danger] = "Login unsucessful"
      redirect_to "/"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action 

  def new
  end

  def create
  end

  def show


  end


  private

  def set_default
    @tags = Tag.all
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :edit, :update]
  before_action :set_default, only: [:show, :edit, :update]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Signup successful! You are now logged in."
      redirect_to root_path
    else
      flash[:danger] = "Signup failed. Please try again."
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile change saved"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Something went wrong"
      redirect_to :back
    end
  end

private

  def set_default
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<h3>Answer this question</h3>

<%= render 'layouts/errors', :object => @answer %>

<div class="container">
  <%= form_for [@question, @answer] do |f| %>
  <div class="form-group">
    <%= f.label :response %>
    <%= f.text_area :response, class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/home/index.html.erb
<h1>This is the homepage</h1>
<% if current_user && current_user.admin %>
  <h3>logged in as admin</h3>
<% end %>

<div class="container">
  <%= link_to "Ask a question", new_question_path %> |
  <%= link_to "Tags", tags_path %>
</div>

<div class="container">
  <div class= "row">
    <div class="col-md-8">
      <% if @questions.any? %>
        <h3>Recent Questions</h3>
        <ul>
          <% @questions.each do |question| %>
            <div class="row">
              <li> <%= link_to question.title, question_path(question)  %> </li>
              <p> Posted by: <%= question.user.username %> | Votes: <%= question.votes %> | Posted: <%= time_ago_in_words(question.created_at) %> ago</p> 

            </div>
          <% end %>
        </ul>
      <% else %>
        <h3>No questions yet!</h3>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if @tags.any? %>
      <h3>Tags:</h3>
        <ul>
          <% @tags.each do |tag| %>
            <li> <%= link_to tag.name, tag_path(tag) %> </li>
          <% end %>
        </ul>
      <% else %>
        <h3>No tags yet</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_flash.html.erb
<div id="flash-container" class="text-center">
  <% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Stack Overflow Clone", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>Logged in as <%=current_user.email%></li>
          <li> <%= link_to "My profile", user_path(current_user) %> </li>
          <li> <%= link_to "Sign Out", logout_path %> </li>
        <% else %>
          <li><%= link_to "Sign In", new_session_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hack Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/flash' %>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<h1>Ask a new Question</h1>

<%= render 'layouts/errors', :object => @question %>

<div class="container">
  <%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body%>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label "Add tags to this post" %>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name  %>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/questions/edit.html.erb
<h1>Edit this question</h1>

<%= render'form' %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="container">

  <h1> <%= @question.title %> </h1>
  <p><%= link_to "Edit", edit_question_path(@question) %> |
    <%= link_to "Delete", question_path(@question), :method => 'delete' %> </p>
  <h3><%= link_to "Upvote", question_path(@question, :vote => 'up'), method: "patch" %> |  <%= link_to "Downvote", question_path(@question, :vote => 'down'), method: "patch" %></h3>


  <h4> Posted by: <%= image_tag @user.avatar.url(:thumb) %> <%= @question.user.username %> </h4>
  <h4> Votes: <%= @question.votes %> </h4>
  <h4> Asked:  <%= @question.created_at.strftime("%b %d %Y") %> ago</h4>


  <p><%= @question.body %> </p>

  <h4>Tags:</h4>
  <% if @question.tags.any? %>
    <% @question.tags.each do |tag| %>
      <%= tag.name %> |
    <% end %>
  <% end %>
</div>

<div class="container">
  <% if @answers.any? %>

    <h3>Answers: </h3>
    <% @answers.each do |answer| %>
      <div class="row">
        <p><%= answer.response %></p>
        <p> Answered by: <%= answer.user.username %> | <%= answer.created_at %></p>
        <p> Votes: <%= answer.votes%></p>
        <h4><%= link_to "Upvote", question_answer_path(@question, answer, :vote => 'up'), method: "patch" %> |
            <%= link_to "Downvote", question_answer_path(@question, answer, :vote => 'down'), method: "patch" %></h4>

      </div>
    <% end %>
  <% end %>
</div>

<div class="container">
  <h3>Add your answer</h3>
  <%= render 'answers/form' %>
</div>

app/views/users/_form.html.erb
<h1>Sign Up</h1>
<%= render 'layouts/errors', :object => @user %>

<%= form_for @user, html: { multipart: true }  do |f| %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :username %><br />
    <%= f.text_field :username, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar, as: :file, class: 'form-control' %>
  </div>

  <div class="form-group"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<%= link_to "Edit my info", edit_user_path(@user) %>

<h3><%= @user.username %></h3>
<h3> <%= @user.email %>  </h3>
<%= image_tag @user.avatar.url(:medium) %>